version: '3.8'
services:

  phpfpm:
    build:
      dockerfile: ./phpfpm/Dockerfile
      context: .
      target: dev_phpfpm
    ports:
      - 8000:8000
    container_name: serverless_php_api_skeleton_phpfpm
    volumes:
      - ../..:/var/www/html
      - ~/.composer/cache:/home/local/.composer/cache
