version: '3.8'
services:

  phpfpm:
    build:
      dockerfile: ./phpfpm/Dockerfile
      context: .
      target: dev_phpfpm
    ports:
      - 8000:8000
    container_name: serverless_php_api_skeleton_phpfpm
    volumes:
      - ../..:/var/www/html
      - ~/.composer/cache:/home/local/.composer/cache

#  mysql:
#    build:
#      dockerfile: ./mysql/Dockerfile
#      context: .
#      target: dev_mysql
#    container_name: mysql
#    ports:
#      - 3306:3306
#    volumes:
#      - ./volumes/databases:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: mysql
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: mysql
#      MYSQL_ROOT_PASSWORD: mysql
